title: "Kurzgeschichten — Leseproben"
description: "Ausgewählte Kurzgeschichten (Leseproben). © Steven Illg. Alle Rechte vorbehalten."
theme: jekyll-theme-cayman
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: "stories"
    values:
      layout: default
